---
version: '3.4'

services:
  sales.data:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=poc
      - POSTGRES_PASSWORD=poc
    volumes:
      - ./database/sales:/var/lib/postgresql/data
  
  products.data:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=poc
      - POSTGRES_PASSWORD=poc
    volumes:
      - ./database/products:/var/lib/postgresql/data

  auth.data:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=poc
      - POSTGRES_PASSWORD=poc
    volumes:
      - ./database/auth:/var/lib/postgresql/data
  
  integration.data:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=poc
      - POSTGRES_PASSWORD=poc
    volumes:
      - ./database/integration:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  mule:
    image: codingtony/mule

  redis:
    image: redis:alpine
  
  web:
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    ports:
      - 4000:4000
      - 4001:4000
      - 4002:4000
    volumes:
      - ./src/backend:/app
    depends_on:
      - rabbitmq
      - redis
      - mule
      - integration.data
      - sales.data
      - auth.data
      - products.data
