apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: auth-data
  name: auth-data
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: auth-data
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: poc
        - name: POSTGRES_USER
          value: poc
        image: postgres:10-alpine
        name: auth-data
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: auth-data
      restartPolicy: Always
      volumes:
      - name: auth-data
        persistentVolumeClaim:
          claimName: auth-data
status: {}
