apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
      - args:
        - yarn
        - start
        image: node:9.4.0
        name: client
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /usr/app
          name: client-claim0
        - mountPath: /usr/app/node-modules
          name: node-modules
      restartPolicy: Always
      volumes:
      - name: client-claim0
        persistentVolumeClaim:
          claimName: client-claim0
      - name: node-modules
        persistentVolumeClaim:
          claimName: node-modules
status: {}
