apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: maintenance
  name: maintenance
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: maintenance
    spec:
      containers:
      - image: maintenance
        name: maintenance
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: maintenance-claim0
      restartPolicy: Always
      volumes:
      - name: maintenance-claim0
        persistentVolumeClaim:
          claimName: maintenance-claim0
status: {}
