apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: mule
  name: mule
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mule
    spec:
      containers:
      - image: mule
        name: mule
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
