apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: sales
  name: sales
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sales
    spec:
      containers:
      - args:
        - ./entrypoint.sh
        env:
        - name: APP_DIR
          value: apps/sales
        - name: RABBITMQ_CONNECTION_STRING
          value: amqp://guest:guest@rabbitmq
        image: sales
        name: sales
        ports:
        - containerPort: 4000
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: sales-claim0
      restartPolicy: Always
      volumes:
      - name: sales-claim0
        persistentVolumeClaim:
          claimName: sales-claim0
status: {}
