apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: sales
  name: sales
spec:
  ports:
  - name: "4001"
    port: 4001
    targetPort: 4000
  selector:
    io.kompose.service: sales
status:
  loadBalancer: {}
