apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: supplier-ws
  name: supplier-ws
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: supplier-ws
    spec:
      containers:
      - image: supplier-ws
        name: supplier-ws
        ports:
        - containerPort: 5050
        resources: {}
      restartPolicy: Always
status: {}
